Ángela María Arias Cód. 201728551

Raúl Andrés Pardo Moreno Cód. 201727367

## Exercise 05

# Neural networks

## 4.1 Little Red Riding Hood Network

Train a neural network to solve the  Little Red Riding Hood problem in sklern and Keras. Try the neural networ with different inputs and report the results.

________________

## 4.2 Boston House Price Prediction

In the next questions we are going to work using the dataset *Boston*. This dataset measures the influence of socioeconomical factors on the price of several estates of the city of Boston. This dataset has 506 instances, each one characterized by 13 features:

* CRIM - per capita crime rate by town
* ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS - proportion of non-retail business acres per town.
* CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
* NOX - nitric oxides concentration (parts per 10 million)
* RM - average number of rooms per dwelling
* AGE - proportion of owner-occupied units built prior to 1940
* DIS - weighted distances to five Boston employment centres
* RAD - index of accessibility to radial highways
* TAX - full-value property-tax rate per 10,000 USD
* PTRATIO - pupil-teacher ratio by town
* B - $1000(Bk - 0.63)^2$ where $Bk$ is the proportion of blacks by town
* LSTAT - % lower status of the population

Output variable:
* MEDV - Median value of owner-occupied homes in 1000's USD

**Note:** In this exercise we are going to predict the price of each estate, which is represented in the `MEDV` variable. It is important to remember that we are always aiming to predict `MEDV`, no matter which explanatory variables we are using. That means, in some cases we will use a subset of the 13 previously mentioned variables, while in other cases we will use all the 13 variables. But in no case we will change the dependent variable $y$.



1. Load the dataset using `from sklearn.datasets import load_boston`.
2. Create a DataFrame using the attribute `.data` from the loading function of Scikit-learn.
3. Assign the columns of the DataFrame so they match the `.feature_names` attribute from the loading function of Scikit-learn. 
4. Assign a new column to the DataFrame which holds the value to predict, that means, the `.target` attribute of the loading function of Scikit-learn. The name of this columns must be `MEDV`.
5. Use the function `.describe()` from Pandas for obtaining statistics about each column.

## 4.3 Feature analysis:

Using the DataFrame generated in the previous section:
* Filter the dataset to just these features:
     * Explanatory: 'LSTAT', 'INDUS', 'NOX', 'RM', 'AGE'
     * Dependent: 'MEDV'.
* Generate a scatter matrix among the features mentioned above using Pandas (`scatter_matrix`) or Seaborn (` pairplot`).
     * Do you find any relationship between the features?
* Generate the correlation matrix between these variables using `numpy.corrcoef`. Also include `MEDV`.
     * Which characteristics are more correlated?
     * BONUS: Visualize this matrix as heat map using Pandas, Matplotlib or Seaborn.

## 4.4 Modeling linear and non linear relationships

* Generate two new subsets filtering these characteristics:
     * $D_1$:  $X = \textit{'RM'}$, $y = \textit{'MEDV'}$
     * $D_2$:  $X = \textit{'LSTAT'}$, $y = \textit{'MEDV'}$
* For each subset, generate a training partition and a test partition using a ratio of $ 70 \% - 30 \% $
* Train a linear regression model on both subsets of data:
     * Report the mean square error on the test set
     * Print the values of $ w $ and $ w_0 $ of the regression equation
     * Generate a graph where you visualize the line obtained by the regression model in conjunction with the training data and the test data
* How does the model perform on $ D_1 $ and $ D_2 $? Why?

## 4.5 Training a regression model

* Generate a 70-30 partitioning of the data **using all the features**. (Do not include the dependent variable `MEDV`)
* Train a linear regression model with the objective of predicting the output variable `MEDV`.
     * Report the mean square error on the test set
* Train a regression model using `MLPRegressor` in order to predict the output variable` MEDV`.
     * Report the mean square error on the test set
* Scale the data so that they have zero mean variance one per feature (only $ X $). You can use the following piece of code:

```python
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
sc_x.fit(X)
X_train_s = sc_x.transform(X_train)
X_test_s = sc_x.transform(X_test)
```
Check more information about `StandardScaler` [here](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

* Train the following models:
     1. Train a linear regression model using the scaled data.
         * Report the mean square error on the test set
     2. Train a regression model using a 2-layer MultiLayer Perceptron (128 neurons in the first and 512 in the second) and with the **scaled data**.
         * Report the mean square error on the test set
     3. Which model has better performance? Why?

In [17]:
#4.1 Little Red Riding Hood Network
#Train a neural network to solve the Little Red Riding Hood problem in sklern and Keras. Try the neural networ with different inputs and report the results.

In [143]:
#4.1.SKlearn

import numpy as np
from sklearn.neural_network import MLPClassifier
X = np.array([[1,1,0,0],[0,1,1,0],[0,0,0,1]])
y = np.array([[1,0,0,0],[0,0,1,1],[0,1,1,0]])

clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(4,3, 4))
clf.fit(X, y)  


#from sklearn.neural_network import MLPClassifier
#X = [[1,1,0,0],[0,1,1,0],[0,0,0,1]]
#y = [[1,0,0,0],[0,0,1,1],[0,1,1,0]]

#clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(4,3, 4))
#clf.fit(X, y)  

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(4, 3, 4), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [144]:
clf.predict([1,1,0,0]) #[1,0,0,0], resultado [1,0,0,0] coincide


C:\Users\harol\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[1, 0, 0, 0]])

In [145]:
clf.predict([0,1,1,0]) #[0,0,1,1], resultado [0,0,1,1] coincide

C:\Users\harol\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[0, 0, 1, 1]])

In [146]:
clf.predict([0,0,0,1]) #[0,1,1,0], resultado [0,1,1,0] coincide

C:\Users\harol\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[0, 1, 1, 0]])

In [147]:
clf.predict([0,1,0,1]) #resultado [0,1,1,0] resultado lógico

C:\Users\harol\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[0, 1, 1, 0]])

In [148]:
clf.predict([1,0,0,1]) #[0,1,1,0] resultado lógico

C:\Users\harol\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[0, 1, 1, 0]])

In [149]:
#4.1.Keras

import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation

X = np.array([[1,1,0,0],[0,1,1,0],[0,0,0,1]])
y = np.array([[1,0,0,0],[0,0,1,1],[0,1,1,0]]) 

#Initializing Neural Network
model = Sequential()

model.add(Dense(units=40, input_dim=4)) #tiene 4 entradas y una capa densa de 40 neuronas(todas las neuronas de la capa anterior se conectan con la capa actual, o sea 80) 
model.add(Activation('relu'))
model.add(Dense(units=4)) 
model.add(Activation('sigmoid'))

model.summary(70)

from keras.optimizers import SGD
model.compile(loss = 'binary_crossentropy',  #funcion de perdida
              optimizer = SGD(lr=0.01, momentum=0.99, decay=0.0, nesterov=False), #SGD es el algoritmo estocasico para optimizar. Lr es el tamaño del paso. Se espera que este paso se sea prudente y se puede ajustar. El momentum es el impulso del vector sobre la superficie de error 
              metrics = ['accuracy'])

  


______________________________________________________________________
Layer (type)                   Output Shape                Param #    
dense_3 (Dense)                (None, 40)                  200        
______________________________________________________________________
activation_3 (Activation)      (None, 40)                  0          
______________________________________________________________________
dense_4 (Dense)                (None, 4)                   164        
______________________________________________________________________
activation_4 (Activation)      (None, 4)                   0          
Total params: 364
Trainable params: 364
Non-trainable params: 0
______________________________________________________________________


In [150]:
model.fit(X, y, epochs=100, verbose=2)

Epoch 1/100
 - 0s - loss: 0.7633 - acc: 0.3333
Epoch 2/100
 - 0s - loss: 0.7623 - acc: 0.4167
Epoch 3/100
 - 0s - loss: 0.7604 - acc: 0.4167
Epoch 4/100
 - 0s - loss: 0.7576 - acc: 0.4167
Epoch 5/100
 - 0s - loss: 0.7539 - acc: 0.4167
Epoch 6/100
 - 0s - loss: 0.7494 - acc: 0.4167
Epoch 7/100
 - 0s - loss: 0.7441 - acc: 0.4167
Epoch 8/100
 - 0s - loss: 0.7380 - acc: 0.4167
Epoch 9/100
 - 0s - loss: 0.7312 - acc: 0.4167
Epoch 10/100
 - 0s - loss: 0.7237 - acc: 0.4167
Epoch 11/100
 - 0s - loss: 0.7157 - acc: 0.4167
Epoch 12/100
 - 0s - loss: 0.7071 - acc: 0.4167
Epoch 13/100
 - 0s - loss: 0.6980 - acc: 0.5000
Epoch 14/100
 - 0s - loss: 0.6886 - acc: 0.5833
Epoch 15/100
 - 0s - loss: 0.6788 - acc: 0.5833
Epoch 16/100
 - 0s - loss: 0.6688 - acc: 0.6667
Epoch 17/100
 - 0s - loss: 0.6587 - acc: 0.6667
Epoch 18/100
 - 0s - loss: 0.6484 - acc: 0.6667
Epoch 19/100
 - 0s - loss: 0.6385 - acc: 0.7500
Epoch 20/100
 - 0s - loss: 0.6287 - acc: 0.7500
Epoch 21/100
 - 0s - loss: 0.6189 - acc: 0.7500
E

In [151]:
#x=orejas grandes, dientes grandes, apuesto, arrugado
#y=grito, abrazo, comida,beso

In [152]:
#print(model.predict(np.array([[1,1,0,0]]))) #[1,0,0,0] coincide

predictions = model.predict(np.array([[1,1,0,0]])) #[1,0,0,0] coincide
rounded = [np.round_(predictions, 0)]
print(rounded)

[array([[1., 0., 0., 0.]], dtype=float32)]


In [153]:
#print(model.predict(np.array([[0,1,1,0]]))) #[0,0,1,1] coincide

predictions = model.predict(np.array([[0,1,1,0]])) #[0,0,1,1] coincide
rounded = [np.round_(predictions, 0)]
print(rounded)

[array([[0., 0., 1., 1.]], dtype=float32)]


In [154]:
#print(model.predict(np.array([[0,0,0,1]]))) #[0,1,1,0] coincide

predictions = model.predict(np.array([[0,0,0,1]])) #[0,1,1,0] coincide
rounded = [np.round_(predictions, 0)]
print(rounded)

[array([[0., 1., 1., 0.]], dtype=float32)]


In [155]:
#print(model.predict(np.array([[0,1,0,1]]))) #[0, 1, 1, 0] resultado lógico

predictions = model.predict(np.array([[0,1,0,1]])) #[0,1,1,0] coincide
rounded = [np.round_(predictions, 0)]
print(rounded)

[array([[0., 0., 1., 0.]], dtype=float32)]


In [156]:
#print(model.predict(np.array([[1,0,0,1]]))) #[0, 1, 1, 0] resultado lógico

predictions = model.predict(np.array([[1,0,0,1]])) #[0,1,1,0] coincide
rounded = [np.round_(predictions, 0)]
print(rounded)

[array([[0., 1., 0., 0.]], dtype=float32)]
